{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "application.fullname" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ template "application.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /app/
            pathType: Prefix
            backend:
              service:
                name: {{ template "application.fullname" . }}-frontend
                port:
                  number: 80
{{- end }}
