apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
  labels:
    app: backend
data:
  DB_HOST: {{ .Values.backend.env.DB_HOST | quote }}
  DB_PORT: {{ .Values.backend.env.DB_PORT | quote }}
  DB_NAME: {{ .Values.backend.env.DB_NAME | quote }}
  DB_USER: {{ .Values.backend.env.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.backend.env.DB_PASSWORD | quote }}
