apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector: 
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}:{{ .Values.backend.tag }}
          imagePullPolicy: Never #O que faz: nunca tenta puxar, força usar a imagem local (só usei pra teste, nao usar em produção).
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: config-map